### ISSUE TITLE
automate testing the preset is working with semantic-release

### ISSUE THREAD

**Issue by sheerlox** [insurgent-lab/conventional-changelog-preset#96]
been trying to automate a dry-run in GitHub Actions so Renovate PRs would fail if the latest `semantic-release` version is not compatible.

this is blocked by https://github.com/semantic-release/semantic-release/issues/1890.

here's what I came with before realizing it was impossible for now (updated `test.yml`):
```yml
name: Lint & Test

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@033f2358d95522973eee35810e35a86fae4a71d8 # v7
      - name: Checkout project
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      - name: Use Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 'lts/*'
      - name: Install packages
        run: npm ci
      - name: Check codestyle compliance
        run: npm run lint
      - name: Setup Git for tests
        run: |
          git config --global user.email "user@test.com"
          git config --global user.name "Test User"
      - name: Run tests
        run: npm run test
      - name: Run Semantic Release (dry-run mode)
        run: npm run release -- --no-ci --dry-run --branches ${{ steps.branch-name.outputs.current_branch }}
        env:
          GITHUB_ACTIONS: ''
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
          fail_ci_if_error: true
```
